name: Update Zen Browser

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # daily

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@main

      - run: ./update.py

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: update packages"
          push_options: '--force'
